use github rest api to lookup release data

diff --git a/install-crit b/install-crit
--- a/install-crit
+++ b/install-crit
@@ -55,7 +55,18 @@ UNAME="$(uname -a)"
 OS="$(uname_to_rust_os "$UNAME")"
 ARCH="$(uname_arch_to_rust_arch "$(uname -m)")"
 TARBALL="$APP-$ARCH-$OS.tgz"
-curl -LO "https://github.com/$GH_FORK/$APP/releases/download/latest/$TARBALL"
+
+RELEASES="$(curl -L "https://api.github.com/repos/mcandre/crit/releases/latest")"
+ASSET="$(echo "$RELEASES" | jq ".assets | first(.[] | select(.name==\"$TARBALL\"))" )"
+
+if [ -z "$ASSET" ]; then
+    echo "error: unsupported platform. uname -a: $(uname -a)" >&2
+    fallback
+    exit 1
+fi
+
+URL="$(echo "$ASSET" | jq -r '.browser_download_url')"
+curl -LO "$URL"
 mkdir -p "$DEST"
 tar -C "$DEST" -xzf "$TARBALL"
 rm -rf "$TARBALL"
