strip version infix from tarballs in preparation for curl automation

diff --git a/port b/port
--- a/port
+++ b/port
@@ -3,12 +3,15 @@ unset IFS
 set -euo pipefail
 
 usage() {
-    printf "Usage: %s [<OPTION>] <banner>\n" "$0"
+    printf "Usage: %s <OPTIONS> <source>\n" "$0"
     printf "\n"
     printf -- "-C <dir>\tChange directory (default: .)\n"
+    printf -- "-a <app>\tCustomize app name (required)\n"
+    printf -- "-h\t\tShow usage menu\n"
 }
 
 DIR='.'
+APP=''
 
 while [ "$#" -ge 1 ]; do
     case "$1" in
@@ -22,6 +25,20 @@ while [ "$#" -ge 1 ]; do
         DIR="$1"
         shift
         ;;
+    '-a')
+        shift
+
+        if [ "$#" -eq 0 ]; then
+            usage
+        fi
+
+        APP="$1"
+        shift
+        ;;
+    '-h')
+        usage
+        exit
+        ;;
     *)
         break
         ;;
@@ -33,22 +50,29 @@ if [ "$#" != '1' ]; then
     exit 1
 fi
 
-BANNER="$1"
-SOURCE="$(readlink -f "$DIR/$BANNER")"
-mkdir -p "$DIR/$BANNER-ports"
-PORTS="$(readlink -f "$DIR/$BANNER-ports")"
+SOURCE="$1"
 
-find "$SOURCE" -type d -depth 1 -print0 | while IFS= read -r -d '' D; do
-    D="${D#"$SOURCE"/}"
+if [ -z "$APP" ]; then
+    usage
+    exit 1
+fi
+
+SOURCE_ABS="$(readlink -f "$DIR/$SOURCE")"
+PORTS="$DIR/$APP-ports"
+mkdir -p "$PORTS"
+PORTS_ABS="$(readlink -f "$PORTS")"
+
+find "$SOURCE_ABS" -type d -depth 1 -print0 | while IFS= read -r -d '' D; do
+    D="${D#"$SOURCE_ABS"/}"
     MODE='--mode=0755'
 
-    if [ "$(find "$SOURCE/$D" -type f -name '*.*')" != '' ]; then
+    if [ "$(find "$SOURCE_ABS/$D" -type f -name '*.*')" != '' ]; then
         MODE='--mode=0644'
     fi
 
-    cd "$SOURCE/$D"
-    tar "$MODE" -czf "$PORTS/$BANNER-$D.tgz" -- *
-    cd "$SOURCE"
+    cd "$SOURCE_ABS/$D"
+    tar "$MODE" -czf "$PORTS_ABS/$APP-$D.tgz" -- *
+    cd "$SOURCE_ABS"
 done
 
-echo "tarballs copied to \"$DIR/$BANNER-ports\""
+echo "tarballs copied to \"$PORTS\""
